# site name
site_name: çˆ¬å‘ç¬”è®°
short_name: è®°

# Master info. It won't work if the one from (author|authorLink|avatar|authorDesc) be written in post.md
webmaster:
  name: å†¯å¤©é¹¤
  avatar: /images/favicon.png
  home: http://fengtianhe.cn
  desc: ä¸€ä¸ªæ¬ğŸ§±çš„åŠ³æ–¯åŸºğŸ˜ï¸ï¸

# CSP Model, true means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
csp_enable: false

# favicon
favicon: /images/favicon.png
# unique avatar
avatar_show: false
avatar_image: /images/favicon.png

# Home page sort type: -1: newer firstï¼Œ1: older first.
home_page_sort: -1
# Home page article shown number
home_article_shown: 10

# Post sticky top support (you need to set top:number in post.md. )
sticky_top:
  enable: true

# your site build time or domain buy time
site_building_time: 01/20/2018

# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
  å‰ç«¯: fe
  åç«¯: rd
  æ•°æ®åº“: db
  æœåŠ¡å™¨: server
  å…¶ä»–: others

# Customize left navigation menus. faName is FontAwesome style name
left_nav_menus:
  - uri: links
    title: å‹é“¾
    faName: fa-links
  - uri: help
    title: å¸®åŠ©
    faName: fa-question-circle


# cover info config
cover_title: ç”¨ä»£ç æ‘‡æ»šè¿™ä¸ªä¸–ç•Œ
cover_description: ä¸€ä¸ªç¨‹åºå‘˜ä¸€æ­¥ä¸€æ­¥çˆ¬å‘çš„è¿‡ç¨‹

# sns url
# ç¤¾äº¤ä¿¡æ¯ï¼Œæ”¯æŒï¼štelegram,instagram,twitter,github,sinaWb,facebook,githubï¼Œå»ºè®®æœ€å¤š4é¡¹
sns:
  #  telegram: http://t.me/kunyintang
  #  instagram: https://www.instagram.com/mtangsir/
  #  twitter: https://twitter.com/tangkunyin
  github: https://github.com/Fengtianhe

# article declare. default content in languages
post_declare: true

# Local search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # unescape html strings to the readable one
  unescape: false

## Analytics setting. Google default
analytics:
  enable: false
  google_analytics_id:

## Google AdSense.
adsense:
  enable: true
  auto: true
  client_id: ca-pub-4443191639930926
  archive_id:
  tags_id:
  post_left_id:
  post_right_id:
  post_bottom_id:
# Git-pages server info
pageServerName: Github
pageServerUrl: https://github.com/Fengtianhe/blog

## Comments settings. Disqus | Gitmentï¼ˆIntroduction: https://imsun.net/posts/gitment-introduction/ï¼‰
comments:
  enable: true
  disqus_shortname: fengtianhe-blog
  gitment:
    repo:
    githubID:
    ClientID:
    ClientSecret:
    lazy: true

## Comments settings. Disqus support only by default.

# Analytics
tentcentAnalyticsId: 500665509
